### ISSUE TITLE
Test fails on aarch64

### ISSUE THREAD

**Issue by eclipseo** [hpcloud/tail#151]
With Go 1.12 on aarch64 only:

```
Testing: github.com/hpcloud/tail
Testing: "/builddir/build/BUILD/tail-a1dbeea552b7c8df4b542c66073e393de198a800/_build/src/github.com/hpcloud/tail"
+ GOPATH=/builddir/build/BUILD/tail-a1dbeea552b7c8df4b542c66073e393de198a800/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
2019/03/08 19:34:22 Waiting for /no/such/file to appear...
2019/03/08 19:34:22 FATAL -- failed to create Watcher
goroutine 21 [running]:
runtime/debug.Stack(0x4000094060, 0x21, 0x0)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x88
github.com/hpcloud/tail/util.Fatal(0xaaaaac6304d6, 0x18, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/tail-a1dbeea552b7c8df4b542c66073e393de198a800/_build/src/github.com/hpcloud/tail/util/util.go:22 +0x8c
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0x400009a880)
	/builddir/build/BUILD/tail-a1dbeea552b7c8df4b542c66073e393de198a800/_build/src/github.com/hpcloud/tail/watch/inotify_tracker.go:219 +0x350
created by github.com/hpcloud/tail/watch.glob..func1
	/builddir/build/BUILD/tail-a1dbeea552b7c8df4b542c66073e393de198a800/_build/src/github.com/hpcloud/tail/watch/inotify_tracker.go:54 +0x110
exit status 1
FAIL	github.com/hpcloud/tail	0.013s
```

**Comment by kxjhcs** [comment]
I have the same problem.
error is：
EpollCreate function not implemented

**Comment by anttygithub** [comment]
I have the same problem.
error is：
EpollCreate function not implemented

**Comment by xlango** [comment]
2020/12/17 15:42:16 FATAL -- failed to create Watcher
goroutine 258 [running]:
runtime/debug.Stack(0x400046e060, 0x21, 0x0)
/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/hpcloud/tail/util.Fatal(0xc568be, 0x18, 0x0, 0x0, 0x0)
/home/go/src/github.com/hpcloud/tail/util/util.go:22 +0x8c
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0x40002c6000)
/home/go/src/github.com/hpcloud/tail/watch/inotify_tracker.go:219 +0x35c
created by github.com/hpcloud/tail/watch.glob..func1
/home/go/src/github.com/hpcloud/tail/watch/inotify_tracker.go:54 +0x110

aarch64   Is there a solution?
